# Generated by Django 5.0.4 on 2024-08-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pessoas', '0002_delete_pessoa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
