# Generated by Django 5.0.4 on 2024-10-08 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_professor_pagamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='pagamento',
            new_name='data_validade',
        ),
    ]
