# Generated by Django 5.0.4 on 2024-08-01 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('disciplina_requisito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas_relacionadas', to='disciplinas.disciplina')),
            ],
        ),
    ]
