# Generated by Django 5.0.4 on 2024-08-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='bibliografia',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
