# Generated by Django 5.0.4 on 2024-08-19 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_codigo'),
        ('disciplinas', '0005_alter_disciplina_disciplina_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
    ]
