# Generated by Django 5.0.4 on 2024-08-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_alter_curso_codigo'),
        ('disciplinas', '0006_alter_disciplina_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
            preserve_default=False,
        ),
    ]
